### ISSUE TITLE
Submission for tip calculator

### ISSUE THREAD

**Issue by hieuvo** [hieuvo/tipsCalculatorSwift#1]
/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Swift submission, hieuvo!

:no_entry_sign: Unfortunately **there are some problems** with your submission:
- I couldn't find how much time you spent on the assignment. Please include the number of hours spent on your assignment in your `README.md`.

**Comment by hieuvo** [comment]
@coderschoolreview I updated, please check

**Comment by coderschoolreview** [comment]
### Thank you for your Swift submission, hieuvo!

 :star: Everything looks good with the format of your submission. We'll be reviewing your submission soon!

**Comment by coderschoolreview** [comment]
:+1: Nice job with the Tip Calculator.

### Some small comments:
- Good usage of the `NSUserDefault` but you should set the saving time for the bill amount as the the requirement ask.
- You should remove the `0.00` when users focus on the text field. It's a little bit weird with this:
  <img width="317" alt="screen shot 2016-02-20 at 5 05 09 pm" src="https://cloud.githubusercontent.com/assets/15702670/13195440/c855d05e-d7e4-11e5-959a-1a856109fd63.png">
- Nice work with setting the percentage editable but the behavior of the segment is quite difficult. And you didn't allow users to choose the default percentage.
- Well done setting the currency.

Congratulation on completing the prework! The result will be emailed you next week.
